Going to read training images
Now going to read paved(asphalt) files (Index: 0)
Now going to read paved(concrete) files (Index: 1)
Complete reading input data. Will Now print a snippet of it
Number of files in Training-set:		500
Number of files in Validation-set:	125
Traceback (most recent call last):
  File "c:\Users\esthe\Documents\GitHub\classification_models\Road Surface Classification Rateke adapted\01Surface Type\train_pytorch.py", line 334, in <module>
    avg_train_loss = train(4)
  File "c:\Users\esthe\Documents\GitHub\classification_models\Road Surface Classification Rateke adapted\01Surface Type\train_pytorch.py", line 289, in train
    wandb.log(train_loss)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 1820, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 1590, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary
Traceback (most recent call last):
  File "c:\Users\esthe\Documents\GitHub\classification_models\Road Surface Classification Rateke adapted\01Surface Type\train_pytorch.py", line 334, in <module>
    avg_train_loss = train(4)
  File "c:\Users\esthe\Documents\GitHub\classification_models\Road Surface Classification Rateke adapted\01Surface Type\train_pytorch.py", line 289, in train
    wandb.log(train_loss)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 1820, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\esthe\anaconda3\envs\SurfaceAI\lib\site-packages\wandb\sdk\wandb_run.py", line 1590, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary